# Generated by Django 4.2.3 on 2023-08-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("helloapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=100)),
            ],
        ),
    ]
