# Generated by Django 4.2.3 on 2023-08-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_task_created_at_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
